-- MySQL Script generated by MySQL Workbench
-- Sat Jul 13 18:29:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vehicle` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vehicle` (
  `ID` VARCHAR(8) NOT NULL,
  `Type` ENUM('Private Car', 'Light Goods Vehicle', 'Motorcycle', 'Private Light Bus', 'Public Light Bus', 'Taxi', 'Private Bus', 'Public Bus', 'Invalid Carriage', 'Government Vehicle', 'Public Bus - Franchised', 'Medium Goods Vehicle', 'Heavy Goods Vehicle', 'Articulated Vehicle', 'Special Purpose Vehicle', 'Motor Tricycle') NOT NULL,
  `OwnerName` VARCHAR(45) NOT NULL,
  `OwnerID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`street`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`street` ;

CREATE TABLE IF NOT EXISTS `mydb`.`street` (
  `NAME` VARCHAR(98) NOT NULL,
  PRIMARY KEY (`NAME`),
  UNIQUE INDEX `Street_UNIQUE` (`NAME` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lamppost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lamppost` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lamppost` (
  `ID` VARCHAR(6) NOT NULL,
  `X` INT NOT NULL,
  `Y` INT NOT NULL,
  `street_NAME` VARCHAR(98) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_lamppost_street1_idx` (`street_NAME` ASC) VISIBLE,
  CONSTRAINT `fk_lamppost_street1`
    FOREIGN KEY (`street_NAME`)
    REFERENCES `mydb`.`street` (`NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`logcache`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`logcache` ;

CREATE TABLE IF NOT EXISTS `mydb`.`logcache` (
  `X` INT NOT NULL,
  `Y` INT NOT NULL,
  `Val` INT NOT NULL DEFAULT 0,
  `vehicle_ID` VARCHAR(8) NOT NULL,
  `street_NAME` VARCHAR(98) NOT NULL,
  INDEX `fk_logcache_vehicle_idx` (`vehicle_ID` ASC) VISIBLE,
  INDEX `fk_logcache_street1_idx` (`street_NAME` ASC) VISIBLE,
  UNIQUE INDEX `vehicle_ID_UNIQUE` (`vehicle_ID` ASC) VISIBLE,
  CONSTRAINT `fk_logcache_vehicle`
    FOREIGN KEY (`vehicle_ID`)
    REFERENCES `mydb`.`vehicle` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logcache_street1`
    FOREIGN KEY (`street_NAME`)
    REFERENCES `mydb`.`street` (`NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`streetbounds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`streetbounds` ;

CREATE TABLE IF NOT EXISTS `mydb`.`streetbounds` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `X_start` INT NOT NULL,
  `Y_start` INT NOT NULL,
  `X_end` INT NOT NULL,
  `Y_end` INT NOT NULL,
  `street_NAME` VARCHAR(98) NOT NULL,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_streetbounds_street1_idx` (`street_NAME` ASC) VISIBLE,
  CONSTRAINT `fk_streetbounds_street1`
    FOREIGN KEY (`street_NAME`)
    REFERENCES `mydb`.`street` (`NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehiclelog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vehiclelog` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vehiclelog` (
  `vehicle_ID` VARCHAR(8) NOT NULL,
  `Log_UUID` INT NOT NULL AUTO_INCREMENT,
  `X` INT NOT NULL,
  `Y` INT NOT NULL,
  `Datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `street_NAME` VARCHAR(98) NOT NULL,
  INDEX `fk_vehiclelog_vehicle1_idx` (`vehicle_ID` ASC) VISIBLE,
  UNIQUE INDEX `Log_UUID_UNIQUE` (`Log_UUID` ASC) VISIBLE,
  PRIMARY KEY (`Log_UUID`),
  INDEX `fk_vehiclelog_street1_idx` (`street_NAME` ASC) VISIBLE,
  CONSTRAINT `fk_vehiclelog_vehicle1`
    FOREIGN KEY (`vehicle_ID`)
    REFERENCES `mydb`.`vehicle` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiclelog_street1`
    FOREIGN KEY (`street_NAME`)
    REFERENCES `mydb`.`street` (`NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehiclewarning`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vehiclewarning` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vehiclewarning` (
  `vehicle_ID` VARCHAR(8) NOT NULL,
  `Datetime` DATETIME NOT NULL DEFAULT current_timestamp(),
  `Reason` VARCHAR(45) NOT NULL DEFAULT 'AUTOMATIC',
  `ID` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_vehiclewarning_vehicle1_idx` (`vehicle_ID` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_vehiclewarning_vehicle1`
    FOREIGN KEY (`vehicle_ID`)
    REFERENCES `mydb`.`vehicle` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS server;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'server' IDENTIFIED BY 'chifatserver';

GRANT SELECT ON TABLE `mydb`.`lamppost` TO 'server';
GRANT SELECT ON TABLE `mydb`.`logcache` TO 'server';
GRANT SELECT ON TABLE `mydb`.`streetbounds` TO 'server';
GRANT SELECT ON TABLE `mydb`.`vehicle` TO 'server';
GRANT INSERT, SELECT ON TABLE `mydb`.`vehiclelog` TO 'server';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`vehicle`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`vehicle` (`ID`, `Type`, `OwnerName`, `OwnerID`) VALUES ('00000000', 'Taxi', 'you', 'you');
INSERT INTO `mydb`.`vehicle` (`ID`, `Type`, `OwnerName`, `OwnerID`) VALUES ('11111111', 'Public Bus', 'me', 'me');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`street`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`street` (`NAME`) VALUES ('TEST');

COMMIT;

USE `mydb`;

DELIMITER $$

DROP TRIGGER IF EXISTS `mydb`.`vehiclelog_AFTER_INSERT` $$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`vehiclelog_AFTER_INSERT` AFTER INSERT ON `vehiclelog` FOR EACH ROW
BEGIN
    DECLARE cache_count INT;
    -- Check if the vehicle ID exists in the logcache
    SELECT COUNT(*) INTO cache_count
    FROM logcache
    WHERE vehicle_ID = NEW.vehicle_ID;

    IF cache_count > 0 THEN
        -- Update the cache if the street_NAME is different
        IF (SELECT street_NAME FROM logcache WHERE vehicle_ID = NEW.vehicle_ID) <> NEW.street_NAME OR (SELECT X FROM logcache WHERE vehicle_ID = NEW.vehicle_ID) <> NEW.X OR (SELECT Y FROM logcache WHERE vehicle_ID = NEW.vehicle_ID) <> NEW.Y THEN
            UPDATE logcache
            SET X = NEW.X,
                Y = NEW.Y,
                street_NAME = NEW.street_NAME,
                Val = 0
            WHERE vehicle_ID = NEW.vehicle_ID;
        ELSE
            -- Increase the value in the cache by one
            UPDATE logcache
            SET Val = Val + 1
            WHERE vehicle_ID = NEW.vehicle_ID;
        END IF;
    ELSE
        -- Insert a new entry in the cache
        INSERT INTO logcache (X, Y, street_NAME, Val, vehicle_ID)
        VALUES (NEW.X, NEW.Y, NEW.street_NAME, 0, NEW.vehicle_ID);
    END IF;
END$$


DROP TRIGGER IF EXISTS `mydb`.`vehiclelog_AFTER_DELETE` $$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`vehiclelog_AFTER_DELETE` AFTER DELETE ON `vehiclelog` FOR EACH ROW
BEGIN
	DELETE FROM logcache WHERE vehicle_ID = OLD.vehicle_ID;
END$$


DELIMITER ;
